---
name: Check pull request message format

on:
  pull_request_target:
    branches:
      - current
      - sagitta
      - equuleus

permissions:
  pull-requests: write
  contents: read

jobs:
  check-pr-title:
    uses: vyos/.github/.github/workflows/check-pr-message.yml@current
    secrets: inherit
